version: "3"
services:
  postgres:
    image: postgres:15
    container_name: "web-app-db-postgres"
    environment:
      - POSTGRES_USER=service
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=service
  app:
    build: ./back
    container_name: "web-app"
    ports:
      - "8080:8080"
    depends_on:
      - web-app-db
