version: "3"
services:
  web-app-db:
    image: postgres
    environment:
      - POSTGRES_ROOT_PASSWORD=password
      - POSTGRES_DATABASE=service
  web-app:
    build: ./back
    ports:
      - "8080:8080"
    depends_on:
      - web-app-db
