version: "3"
services:
  postgres:
    image: postgres:15-alpine
    container_name: "web-app-db-postgres"
    environment:
      - POSTGRES_USER=service
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=service
  app:
    build: ./back
    container_name: "web-app"
    ports:
      - "8080:8080"
      - "8000:8000"
    environment:
      - JPDA_ADDRESS=8000
      - JPDA_TRANSPORT=dt_socket
    depends_on:
      - postgres
    command: "/usr/local/tomcat/bin/catalina.sh jpda run"
    restart: always
